name: 'analytics_interview'
version: '1.0.0'
config-version: 2

profile: 'analytics_interview'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  analytics_interview:
    bronze:
      materialized: table
    silver:
      materialized: table